-- FIND THE TOTAL NUMBER OF ORDERS
-- FIND THE TOTAL SALES OF ALL ORDERS
-- FIND THE AVG SALES
-- FIND THE HIGHEST AND LOWEST SALES

SELECT 
COUNT(*) TOTAL_NR_ORDERS,
SUM(SALES) TOTAL_SALES,
AVG(SALES) AVG_SALES,
MAX(SALES) HIGHEST_SALES,
MIN(SALES) LOWEST_SALES
FROM orders
GROUP BY customer_id;

