-- FIND THE AVERAGE SALES FOR ALL ORDERS
-- AND FIND THE AVERAGE SALES FOR EACH PRODUCT
-- ADDITIONALLY PROVIDE DETAILS SUCH AS ORDERID AND ORDERDATE

SELECT 
ORDERID,
ORDERDATE,
AVG(SALES) OVER() AVG_SALES,
PRODUCTID,
AVG(SALES) OVER(PARTITION BY PRODUCTID) PRODUCT_WISE_AVG
FROM SALES.Orders