-- FIND ALL THE ORDERS WHERE SALES ARE HIGHER THAN THE AVERAGE SALES ACROSS ALL ORDERS

SELECT 
ORDERID,
SALES,
AVG_SALES
FROM(
	SELECT 
	ORDERID,
	SALES,
	AVG(SALES) OVER() AS AVG_SALES
	FROM SALES.Orders
)T
WHERE SALES > AVG_SALES