-- FIND THE AVERAGE SCORES OF CUSTOMERS
-- ADDITIONALLY PROVIDE DETAILS SUCH AS CUSTOMERID AND LASTNAME

SELECT 
CUSTOMERID,
LASTNAME,
SCORE,
AVG(SCORE) OVER() AVG_SCORE_WITH_NULL,
AVG(COALESCE(SCORE,0)) OVER() AVG_SCORE_WITHOUT_NULL
FROM SALES.CUSTOMERS