-- USE CASE FOR ROW_NUMBER()-> BOTTOM-N ANALYSIS
-- FIND THE LOWEST 2 CUSTOMERS BASED ON THEIR TOTAL SALES
SELECT * FROM(
SELECT
	CUSTOMERID,
	SUM(SALES) TOTAL_SALES,
	ROW_NUMBER() OVER(ORDER BY SUM(SALES)) RANK_CUSTOMERS
FROM SALES.Orders
GROUP BY CustomerID
)T
WHERE RANK_CUSTOMERS <= 2 