-- COUNT HOW MANY TIMES EACH CUSTOMER HAS MADE AN ORDER WITH SALES GREATER THAN 30

SELECT 
CUSTOMERID,
SUM(
CASE 
	WHEN SALES>30 THEN  1
	ELSE 0
END) TOTAL_ORDERS_HIGH,
COUNT(*) TOTAL_ORDERS
FROM SALES.Orders
GROUP BY CustomerID 