-- RETRIVE EMPLOYEE DETAILS WITH GENDER DISPLAYED AS FULL TEXT

SELECT 
EmployeeID,
Gender,
CASE 
	WHEN GENDER = 'M' THEN 'MALE'
	WHEN GENDER = 'F' THEN 'FEMALE'
	ELSE 'N\A'
END GENDER_FULL
FROM SALES.Employees