-- NORMAL FORM 
SELECT 
CUSTOMERID,FIRSTNAME,LASTNAME,COUNTRY,
CASE 
	WHEN COUNTRY = 'Germany' THEN 'GE'
	WHEN COUNTRY = 'USA' THEN 'US'
	ELSE 'N/A'
	END 'ABBREVIATED COUNTRY CODE'
FROM SALES.Customers;

-- QUICK FORM
SELECT 
CUSTOMERID,FIRSTNAME,LASTNAME,COUNTRY,
CASE COUNTRY
	WHEN 'Germany' THEN 'GE'
	WHEN 'USA' THEN 'US'
	ELSE 'N/A'
	END 'ABBREVIATED COUNTRY CODE'
FROM SALES.Customers;