-- GENRATE THE REPORT SHOWING THE TOTAL SALES FOR EACH CATEGORY
-- HIGH: IF THE SALES IS HIGHER THAN 50
-- MEDIUM: IF THE SALES BETWEEN 20 AND 50 
-- LOW : IF THE SALES IS EQUAL OR LOWER THAN 20

-- SORT THE RESULT FROM HIGHEST TO LOWEST

SELECT 
CATEGORY,
SUM(Sales) AS TOTAL_SALES
FROM(

SELECT 
SALES,
CASE 
WHEN SALES>50 THEN 'HIGH'
WHEN SALES>=20 AND SALES<=50 THEN 'MEDIUM'
WHEN SALES<=20 THEN 'LOW'
END CATEGORY
FROM SALES.Orders
)t
GROUP BY CATEGORY
ORDER BY TOTAL_SALES DESC