-- RETRIVE CUSTOMERS DETAILS WITH ABBREVIATED COUNTRY CODE 

SELECT 
CUSTOMERID,FIRSTNAME,LASTNAME,COUNTRY,
CASE 
	WHEN COUNTRY = 'Germany' THEN 'GE'
	WHEN COUNTRY = 'USA' THEN 'US'
	ELSE 'N/A'
	END 'ABBREVIATED COUNTRY CODE'
FROM SALES.Customers;



SELECT DISTINCT COUNTRY FROM SALES.Customers;