-- FIND THE AVERAGE SCORE OF THE CUSTOMERS AND TREAT NULLS AS 0
-- AND ADDITIONAL PROVIDE DETAILS ABOUT CUSTOMER'S FIRST AND LAST NAME 

SELECT 
FirstName,
LastName,
SCORE,
AVG(
CASE 
	WHEN Score IS NULL THEN 0
	ELSE Score
END) OVER() AVG_SCORE_CLEAN
FROM SALES.Customers