SELECT
CAST('123' AS INT) AS [STRING TO INT],
CAST(123 AS VARCHAR) AS [INT TO STRING],
CAST('2025-01-01' AS DATE) AS [STRING TO DATE],
CAST('2025-01-01' AS DATETIME2) AS [STRING TO DATETIME],
CREATIONTIME,
CAST(CREATIONTIME AS DATE) AS [DATE ONLY]
FROM SALES.Orders