--GET ALL CUSTOMERS ALONG WITH THEIR ORDERS , BUT ONLY FOR THE CUSTOMERS WHO HAVE PLACED AN ORDER
SELECT * 
FROM CUSTOMERS AS C
RIGHT JOIN ORDERS AS O
ON C.ID = O.customer_id
WHERE C.ID IS NOT NULL;

SELECT * 
FROM CUSTOMERS AS C
LEFT JOIN ORDERS AS O
ON C.ID = O.customer_id
WHERE O.customer_id IS NOT NULL;