-- CHECK WHETHER TABLE ORDER CONTAINS DUPLICATE ROWS OR NOT 
SELECT * FROM
(
	SELECT 
	ORDERID,
	COUNT(*) OVER( PARTITION BY ORDERID) PK_CHECK
	FROM SALES.OrdersArchive
)T
WHERE PK_CHECK > 1

