-- DISPLAY THE FULL NAME OF THE CUSTOMERS IN A SINGLE FIELD 
-- BY MERGING THEIR FIRST AND LAST NAME 
-- AND ADD 10 BONUS POINTS TO EACH CUSTOMER'S SCORE 

SELECT 
CustomerID,
FirstName,
LastName,
FirstName+' '+COALESCE(LastName,' ') AS FULLNAME ,
Score,
COALESCE(Score,0) + 10 AS SCORE_WITH_BONUS
FROM SALES.Customers