-- FIND THE AVERAGE SCORE OF THE CUSTOMERS

SELECT 
CustomerID,
Score,
COALESCE(SCORE,0) AS SCORE_2,
AVG(SCORE) OVER() AVG_SCORES,
AVG(COALESCE(SCORE,0)) OVER () AS AVG_SCORES_WITHOUT_NULL
FROM SALES.Customers