SELECT
CONVERT(INT,'123') AS STRING_TO_INT,
CONVERT(DATE,'2025-02-20') STRING_TO_DATE,
CREATIONTIME,
CONVERT(DATE,CREATIONTIME) AS DATE_ONLY,
CONVERT(VARCHAR,CREATIONTIME,32) AS [USA.STD_STYLE:32],
CONVERT(VARCHAR,CREATIONTIME,34) AS [EURO.STD_STYLE:34]
FROM SALES.Orders