-- FIND THE TOTAL NUMBER OF CUSTOMERS,ADDITIONALLY PROVIDE ALL CUSTOMER DETAILS
-- FIND THE TOTAL NUMBER OF SCORES FOR THE CUSTOMER
SELECT
*,
COUNT(*) OVER() [TOTAL CUSTOMERS],
COUNT(SCORE) OVER() [TOTAL SCORE],
COUNT(*) OVER() [TOTAL SCORE]   -- IT WILL COUNT THE NULL VALUE ALSO
FROM SALES.Customers