-- FIND THE TOTAL NUMBER OF ORDERS
-- ADDITTIONALLY PROVIDE ORDERID AND ORDERDATE
-- FIND THE TOTAL NUMBER OF ORDERS FOR EACH CUSTOMER

SELECT 
ORDERID,
ORDERDATE,
CUSTOMERID,
COUNT(ORDERID) OVER() [ TOTAL ORDERS],
COUNT(*) OVER(PARTITION BY CUSTOMERID) [ORDER BY CUSTOMERS]
FROM SALES.Orders


