-- FIND THE PRODUCTS THAT FALL WITHIN THE HIGHEST 40% OF PRICES
SELECT 
PRODUCT,
PRICE,
DIST_RANK,
CONCAT(DIST_RANK * 100,'%') [PERCENTAGE]
FROM(
SELECT 
	PRODUCT,
	PRICE,
	CUME_DIST() OVER(ORDER BY PRICE DESC) DIST_RANK
FROM SALES.PRODUCTS
)T
WHERE DIST_RANK <= 0.4