SELECT 
ORDERID,
CREATIONTIME,
DATENAME(MONTH,CREATIONTIME) AS MONTH_NAME,
DATENAME(WEEKDAY,CREATIONTIME) AS WEEKDAY_NAME,
DATENAME(DAY,CREATIONTIME) AS DAY_NAME --IT WILL BE STORED AS STRING 
FROM SALES.ORDERS