SELECT
OrderID,
CreationTime,
FORMAT(CREATIONTIME,'MM-dd-yyyy') USA_FORMAT,
FORMAT(CREATIONTIME,'dd-MM-yyyy') EUROPE_FORMAT,

FORMAT(CREATIONTIME,'dd') dd,
FORMAT(CREATIONTIME,'ddd') D_NAME_SHORT,
FORMAT(CREATIONTIME,'dddd') D_NAME_FULL,

FORMAT(CREATIONTIME,'MM') MM,
FORMAT(CREATIONTIME,'MMM') M_NAME_SHORT,
FORMAT(CREATIONTIME,'MMMM') M_NAME_FULL

FROM SALES.Orders