SELECT
OrderDate,
DATEADD(YEAR,2,ORDERDATE) [AFTER 2YR],
DATEADD(MONTH,2,ORDERDATE) [AFTER 2MONTH],
DATEADD(DAY,2,ORDERDATE) [AFTER 2DAY],
DATEADD(DAY,-2,ORDERDATE) [BEFORE 2DAY]
FROM SALES.Orders