--FIND THE AVERAGE SHIPPING DURATION IN DAYS FOR EACH MONTH

SELECT
MONTH(ORDERDATE) AS ORDER_DATE,
AVG(DATEDIFF(DAY,ORDERDATE,SHIPDATE)) [AVG SHIP]
FROM SALES.Orders
GROUP BY MONTH(OrderDate)
