SELECT                                 -- ALL THE RECORDS WILL BE STORED IN INT
OrderID,
CREATIONTIME,
DATEPART(YEAR,CREATIONTIME) YEAR_DP,
DATEPART(MONTH,CREATIONTIME) MONTH_DP,
DATEPART(DAY,CREATIONTIME) DAY_DP,
DATEPART(QUARTER,CREATIONTIME) QUARTER_DP,
DATEPART(HOUR,CREATIONTIME) HOUR_DP,
DATEPART(WEEKDAY,CREATIONTIME) WEEKDAY_DP,
DATEPART(WEEK,CREATIONTIME) WEEK_DP
FROM SALES.ORDERS



