-- TIME GAP ANALYSIS
-- FIND THE NUMBER OF DAYS BETWEEN EACH ORDER AND PREVIOUS ORDER
-- LAG() IS USED TO RETRIVE THE VALUE FROM PREVIOUS VALUE 

SELECT
ORDERID,
ORDERDATE,
LAG(ORDERDATE) OVER (ORDER BY ORDERDATE) [PREVIOUS ORDER DATE],
DATEDIFF(DAY,LAG(ORDERDATE) OVER (ORDER BY ORDERDATE),ORDERDATE) [NUMBER OF DAYS]
FROM SALES.Orders

