--HOW MANY ORDERS WERE PLACED EACH YEAR

SELECT
DATEPART(YEAR,CREATIONTIME) AS DATA_YEAR,
COUNT(*)
FROM SALES.Orders
GROUP BY DATEPART(YEAR,CREATIONTIME);

SELECT
YEAR(ORDERDATE),
COUNT(*) AS NO_OF_ORDERS
FROM SALES.Orders
GROUP BY YEAR(ORDERDATE);