-- FIND THE TOTAL SALES OF EACH PRODUCT

SELECT
	PRODUCTID,
	SUM(Sales) TOTAL_SALES
FROM Sales.Orders
GROUP BY PRODUCTID;

-- FIND THE TOTAL SALES OF EACH PRODUCT
-- ADDITIONALLY PROVIDE DETAILS SUCH AS ORDERID AND ORDERDATE
SELECT
	ORDERID,
	PRODUCTID,
	ORDERDATE,
	SUM(SALES) OVER(PARTITION BY PRODUCTID) TOTAL_SALES
	FROM SALES.ORDERS;