-- -- ROW_NUMBER() USECASE - IDENTIFYING DUPLICATES

-- IDENTIFY DUPLICATES ROWS IN THE TABLE ORDER ARCHIVE AND RETURN A CLEAN RESULT WIHOUT ANY DUPLICATES

SELECT *
FROM (
	SELECT 
		ROW_NUMBER() OVER(PARTITION BY ORDERID ORDER BY CREATIONTIME DESC) RN,
		*
	FROM SALES.OrdersArchive
	)T
WHERE RN = 1