-- IDENTIFY THE CUSTOMERS WHO HAVE NO SCORE 


SELECT 
*
FROM SALES.CUSTOMERS
WHERE Score IS NULL;

-- IDENTIFY ALL THE CUSTOMERS WHO HAVE SCORES

SELECT * FROM SALES.Customers
WHERE SCORE IS NOT NULL;