-- SORT THE CUSTOMER FROM LOWEST TO HIGHEST SCORES WITH NULLS APEARING LAST

SELECT
CustomerID,
Score,
CASE WHEN SCORE IS NULL THEN 1 ELSE 0 END FLAG
FROM SALES.Customers
ORDER BY CASE WHEN SCORE IS NULL THEN 1 ELSE 0 END,SCORE