-- LIST ALL DETAILS FOR THE CUSTOMERS WHO HAVE NOT PLACED ANY ORDER

SELECT 
A.* ,
B.OrderID
FROM SALES.Customers AS A
LEFT JOIN  SALES.Orders AS B
ON A.CustomerID = B.CustomerID
WHERE B.CustomerID IS NULL;