-- LEAD() & LAG() USE CASE
/* CUSTOMER RETENTION ANALYSIS(MEASURE CUSTOMER BEHAVIOR AND LOYALTY TO HELP BUSINESSES BUILD STRONG
 RELATIONSHIPS WITH CUSTOMERS */

 -- IN ORDER TO ANALYZE CUSTOMER LOYALTY,RANK CUSTOMERS BASED ON AVERAGE DAYS BETWEEN THEIR ORDERS
SELECT 
 CUSTOMERID,
 AVG(DAYS_UNTIL_NEXT_ORDER) AVG_DAYS,
 RANK() OVER(ORDER BY AVG(DAYS_UNTIL_NEXT_ORDER)) RANKING
FROM(
		 SELECT 
			 ORDERID,
			 CUSTOMERID,
			 ORDERDATE [CURRENT ORDER],
			 LEAD(ORDERDATE) OVER(PARTITION BY CUSTOMERID ORDER BY ORDERDATE) [NEXT ORDER],
			 DATEDIFF(DAY,ORDERDATE,LEAD(ORDERDATE) OVER(PARTITION BY CUSTOMERID ORDER BY ORDERDATE)) DAYS_UNTIL_NEXT_ORDER
		 FROM SALES.Orders
)T
 GROUP BY CUSTOMERID