-- ANALYZE THE MONTH-OVER-MONTH(MOM) PERFORMANCE BY FINDING THE PERCENTAGE CHANGE IN SALES BETWEEN 
-- CURRENT AND PREVIOUS MONTH

-- LEAD() & LAG() USE CASE
-- TIME SERIES ANALYSIS(THE PROCESS OF ANALYSING THE DATA TO UNDERSTAND THE PATTERNS ,TRENDS AND BEHAVIOURS OVER TIME)

SELECT 
*,
CURRENT_MONTH_SALES - PREVIOUS_MONTH_SALES [MOM CHANGE],
ROUND(CAST((CURRENT_MONTH_SALES - PREVIOUS_MONTH_SALES) AS FLOAT)/PREVIOUS_MONTH_SALES*100,1) AS MOM_PERCENTAGE
FROM(
		SELECT 
			MONTH(OrderDate) ORDER_MONTH,
			SUM(SALES) CURRENT_MONTH_SALES,
			LAG(SUM(SALES)) OVER(ORDER BY MONTH(ORDERDATE)) PREVIOUS_MONTH_SALES
		FROM SALES.Orders
			GROUP BY MONTH(OrderDate)
)T