/*
RETRIVE THE FIRST TWO CHARACTERS AND
LAST TWO CHARACTERS OF EACH FIRST_NAME
*/

SELECT 
FIRST_NAME,
LEFT(TRIM(FIRST_NAME),2) AS FIRST_2_CHAR,
RIGHT(TRIM(FIRST_NAME),2) AS LAST_2_CHAR
FROM CUSTOMERS