-- FIND THE DEVIATION OF EACH SALES FROM THE MINIMUM MAXIMUM SALES AMOUNTS
SELECT 
MAX(SALES) OVER() [MAX SALES],
MIN(SALES) OVER() [MIN SALES],
SALES - MIN(SALES) OVER() [DEVIATION FROM MIN],
MAX(SALES)OVER() - SALES [DEVIATION FROM MAX]
FROM SALES.Orders