-- FIND THE HIGHEST AND LOWEST SALES ACROSS ALL ORDERS AND HIGHEST AND LOWEST SALES FOR EACH PRODUCTS
-- ADDITIONALLY PROVIDE DETAILS SUCH AS ORDERID AND ORDER DATE 

SELECT 
PRODUCTID,
ORDERID,
ORDERDATE,
MAX(SALES) OVER() MAX_SALES,
MIN(SALES) OVER() MIN_SALES,

MAX(SALES) OVER(PARTITION BY PRODUCTID) W_MAX_SALES_BY_PRODUCT,
MIN(SALES) OVER(PARTITION BY PRODUCTID) W_MIN_SALES_BY_PRODUCT
FROM SALES.Orders