SELECT
ORDERID,
SALES,
NTILE(1) OVER(ORDER BY SALES DESC) ONE_BUCKET,
NTILE(2) OVER(ORDER BY SALES DESC) TWO_BUCKET,
NTILE(3) OVER(ORDER BY SALES DESC) THREE_BUCKET,  -- LARGER GROUPS COMES FIRST
NTILE(4) OVER(ORDER BY SALES DESC) FOUR_BUCKET
FROM SALES.Orders