-- SEGMENT ALL THE ORDERS INTO 3 CATEGORIES HIGH,MEDIUM AND LOW SALES 
SELECT *,
CASE
	WHEN RANKING = 1 THEN 'HIGH'
	WHEN RANKING = 2 THEN 'MEDIUM'
	WHEN RANKING = 3 THEN 'LOW' 
END SALES_SEGMENTATIONS

FROM (
SELECT
OrderID,
SALES,
NTILE(3) OVER(ORDER BY SALES DESC) RANKING
FROM SALES.Orders
)T
