-- FIND THE PERCENTAGE CONTRIBUTION OF EACH PRODUCTS SALES TO THE TOTAL SALES


	SELECT
	OrderID,
	ProductID,
	SALES,
	SUM(SALES) OVER() AS TOTAL_SALES,
	ROUND(CAST(SALES AS FLOAT)/SUM(SALES) OVER() *100,2) PERCENTAGE_CALC
	FROM SALES.Orders
