-- RANK EACH ORDER BASED ON THEIR SALES FROM HIGHEST TO LOWEST
-- ADDITIONALLY PROVIDE DETAILS ABOUT ORDERID AND ORDERDATE

SELECT 
	OrderID,
	OrderDate,
	Sales,
	RANK() OVER(ORDER BY SALES DESC) RANKING
FROM SALES.Orders