-- CALCULATE THE MOVING AVERAGE OF SALES OF EACH PRODUCT OVER TME
-- CALCULATE THE MOVING AVERAGE OF SALES OF EACH PRODUCT OVER TME,INCLUDING ONLY THE NEXT ORDER
SELECT
	ORDERID,
	PRODUCTID,
	ORDERDATE,
	SALES,
	AVG(SALES) OVER(PARTITION BY PRODUCTID) [AVG BY PRODUCT],
	AVG(SALES) OVER(PARTITION BY PRODUCTID ORDER BY ORDERDATE) [MOVING AVERAGE],
	AVG(SALES) OVER(PARTITION BY PRODUCTID ORDER BY PRODUCTID 
	ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING) [ROLLING AVERAGE]

FROM SALES.ORDERS