-- RANK THE ORDERS BASED ON THEIR SALES FROM HIGHEST TO LOWEST

SELECT 
	ORDERID,
	ORDERDATE,
	PRODUCTID,
	SALES,
	ROW_NUMBER() OVER(ORDER BY SALES DESC) [ROW_NUMBER() RANK],
	RANK()       OVER(ORDER BY SALES DESC) [RANK() RANK],
	DENSE_RANK() OVER(ORDER BY SALES DESC) [DENSE_RANK() RANK]
FROM SALES.Orders