--SHOW CREATIONTIME USING THE FOLOWING FORMAT
--DAY WED JAN Q1 2025 12:34:56 PM

SELECT 
CreationTime,
'DAY '+FORMAT(CREATIONTIME,'ddd MMM Q')
+DATENAME(QUARTER,CreationTime)
+FORMAT(CREATIONTIME,' yyyy hh:mm:ss tt') AS ANSWER
FROM SALES.Orders