-- FIND THE SALES ACROSS ALL ORDERS AND TOTAL SALES FOR EACH PRODUCT
-- ADDITIONALLY PROVIDE DEATILS SUCH AS ORDERID AND ORDERDATE
SELECT
OrderID,
OrderDate,
PRODUCTID,
Sales,
SUM(SALES) OVER() [TOTAL SALES],
SUM(SALES) OVER(PARTITION BY PRODUCTID) [TOTAL SALES FOR EACH PRODUCT]

FROM SALES.Orders