-- USE CASE FOR ROW_NUMBER()-> TOP-N ANALYSIS
-- FIND THE TOP HIGHEST SALES FOR EACH PRODUCT
SELECT *
FROM(
	SELECT 
		PRODUCTID,
		SALES,
		ORDERID,
		ROW_NUMBER() OVER(PARTITION BY PRODUCTID ORDER BY SALES DESC)[RANK]
	FROM SALES.Orders)T
WHERE RANK=1