-- FIND THE TOTAL SALES ACROSS ALL ORDERS 
-- FIND THE TOTAL SALES FOR EACH PRODUCT
-- FIND THE TOTAL SALES FOR PRODUCT ID AND ORDERSTATUS
--ADDITIONALLY PROVIDE DETAILS SUCH AS ORDERID AND ORDERDATE

SELECT 
	ORDERID,
	OrderDate,
	ProductID,
	OrderStatus,
	Sales,
	SUM(SALES) OVER() TOTAL_SALES,
	SUM(SALES) OVER(PARTITION BY PRODUCTID) TOTAL_SALES_PRODUCTWISE,
	SUM(SALES) OVER(PARTITION BY PRODUCTID,ORDERSTATUS) TOTAL_SALES_PID_ORDERSTATUS
FROM SALES.Orders