-- FIND THE TOTAL SALES FOR EACH ORDER STATUS ,ONLY FOR TWO PRODUCTS 101 AND 102

SELECT 
ORDERSTATUS,
PRODUCTID,
ORDERDATE,
SUM(SALES) OVER(PARTITION BY ORDERSTATUS) TOTAL_SALES
FROM SALES.Orders
WHERE ProductID IN (101,102)

