-- FIND THE TOTAL SALES FOR EACH PRODUCT,
--ADDITIONALLY PROVIDE DETAILS SUCH AS ORDERID AND ORDERDATE

SELECT 
	ORDERID,
	OrderDate,
	ProductID,
	SUM(SALES) OVER(PARTITION BY PRODUCTID) TOTAL_SALES_PRODUCTWISE
FROM SALES.Orders